### ISSUE TITLE
Calculation of time tag.

### ISSUE THREAD

**Issue by pangzss** [PolyU-ChenLab/ETBench#1]
Thank you for contributing this great work!

While browsing your code, I found some this line kinda confusing:
https://github.com/PolyU-ChenLab/ETBench/blob/41ff2cdf0a9f77ded3a54515e19b1b8a56a20fa9/etchat/utils/io.py#L49

If I understood correctly, "tag" represents the frame timestamps. Then should it be division instead of multiplication?

**Comment by yeliudev** [comment]
Yes there is a typo here. The correct form should be `tag = [round(i / avg_fps, 1) for i in frame_idx]`. But it won't affect the overall performance as the frame timestamps are not used without explicitly setting `--use_time_tag`. I'll fix it very soon. Thanks for pointing it out!

**Comment by pangzss** [comment]
Thank you for replying to the above question.

Another question is about the update of the cache_position:
https://github.com/PolyU-ChenLab/ETBench/blob/41ff2cdf0a9f77ded3a54515e19b1b8a56a20fa9/etchat/model/etchat_arch.py#L383-L386

In my understanding, if we do inference by calling Tranformers' model.generate(), the creation and updates of cache_position will be automatically handled. Why did you choose to manually do it here?

Also, could you explain the purpose of iteratively adding the length of frame tokens to cache_position here: "cache_position = cache_position + self.cache_img_state.size(0) - 1"?

**Comment by yeliudev** [comment]
> Why manually handling the `cache_position` here?

This is because the class `ETChatMetaForCausalLM` derives from `LlamaForCausalLM`, which is a language-only model that cannot handle visual inputs. After inserting the visual tokens in `self.prepare_multimodal_data`, `cache_position` should also be updated to match the updated sequence length.

> Why iteratively adding the length of frame tokens to `cache_position`?

`cache_position` has to be updated in every inference step to ensure its correct value, as the added frame token length would be removed before each step.

We only tested this implementation on `transformers==4.44.2`. You may double-check the value of `cache_position` in each step if you encounter any issues during generation.
